/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMembershipsRouteImport } from './routes/_authenticated/memberships'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedDeliveryRouteRouteImport } from './routes/_authenticated/delivery/route'
import { Route as AuthenticatedChefRouteRouteImport } from './routes/_authenticated/chef/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedDeliveryIndexRouteImport } from './routes/_authenticated/delivery/index'
import { Route as AuthenticatedChefIndexRouteImport } from './routes/_authenticated/chef/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedItemsChefItemIdRouteImport } from './routes/_authenticated/items.$chefItemId'
import { Route as AuthenticatedDeliveryProfileRouteImport } from './routes/_authenticated/delivery/profile'
import { Route as AuthenticatedDeliveryJobsRouteImport } from './routes/_authenticated/delivery/jobs'
import { Route as AuthenticatedDeliveryActiveRouteImport } from './routes/_authenticated/delivery/active'
import { Route as AuthenticatedChefsChefIdRouteImport } from './routes/_authenticated/chefs.$chefId'
import { Route as AuthenticatedChefVerifyRouteImport } from './routes/_authenticated/chef/verify'
import { Route as AuthenticatedChefProfileRouteImport } from './routes/_authenticated/chef/profile'
import { Route as AuthenticatedChefPayoutsRouteImport } from './routes/_authenticated/chef/payouts'
import { Route as AuthenticatedChefOrdersRouteImport } from './routes/_authenticated/chef/orders'
import { Route as AuthenticatedChefMenuRouteImport } from './routes/_authenticated/chef/menu'
import { Route as AuthenticatedChefInsightsRouteImport } from './routes/_authenticated/chef/insights'
import { Route as AuthenticatedAdminZonesRouteImport } from './routes/_authenticated/admin/zones'
import { Route as AuthenticatedAdminReceiptsRouteImport } from './routes/_authenticated/admin/receipts'
import { Route as AuthenticatedAdminItemsRouteImport } from './routes/_authenticated/admin/items'
import { Route as AuthenticatedAdminGatewaysRouteImport } from './routes/_authenticated/admin/gateways'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin/drivers'
import { Route as AuthenticatedAdminChefsRouteImport } from './routes/_authenticated/admin/chefs'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedChefVerifyPayoutRouteImport } from './routes/_authenticated/chef/verify.payout'
import { Route as AuthenticatedChefVerifyIdRouteImport } from './routes/_authenticated/chef/verify.id'
import { Route as AuthenticatedChefVerifyHealthRouteImport } from './routes/_authenticated/chef/verify.health'
import { Route as AuthenticatedChefVerifyCapacityRouteImport } from './routes/_authenticated/chef/verify.capacity'
import { Route as AuthenticatedChefVerifyAddressRouteImport } from './routes/_authenticated/chef/verify.address'
import { Route as AuthenticatedAdminChefsChefIdRouteImport } from './routes/_authenticated/admin/chefs.$chefId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembershipsRoute =
  AuthenticatedMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveryRouteRoute =
  AuthenticatedDeliveryRouteRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChefRouteRoute = AuthenticatedChefRouteRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryIndexRoute =
  AuthenticatedDeliveryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeliveryRouteRoute,
  } as any)
const AuthenticatedChefIndexRoute = AuthenticatedChefIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChefRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemsChefItemIdRoute =
  AuthenticatedItemsChefItemIdRouteImport.update({
    id: '/items/$chefItemId',
    path: '/items/$chefItemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryProfileRoute =
  AuthenticatedDeliveryProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDeliveryRouteRoute,
  } as any)
const AuthenticatedDeliveryJobsRoute =
  AuthenticatedDeliveryJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedDeliveryRouteRoute,
  } as any)
const AuthenticatedDeliveryActiveRoute =
  AuthenticatedDeliveryActiveRouteImport.update({
    id: '/active',
    path: '/active',
    getParentRoute: () => AuthenticatedDeliveryRouteRoute,
  } as any)
const AuthenticatedChefsChefIdRoute =
  AuthenticatedChefsChefIdRouteImport.update({
    id: '/chefs/$chefId',
    path: '/chefs/$chefId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChefVerifyRoute = AuthenticatedChefVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedChefRouteRoute,
} as any)
const AuthenticatedChefProfileRoute =
  AuthenticatedChefProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedChefRouteRoute,
  } as any)
const AuthenticatedChefPayoutsRoute =
  AuthenticatedChefPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedChefRouteRoute,
  } as any)
const AuthenticatedChefOrdersRoute = AuthenticatedChefOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedChefRouteRoute,
} as any)
const AuthenticatedChefMenuRoute = AuthenticatedChefMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedChefRouteRoute,
} as any)
const AuthenticatedChefInsightsRoute =
  AuthenticatedChefInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedChefRouteRoute,
  } as any)
const AuthenticatedAdminZonesRoute = AuthenticatedAdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReceiptsRoute =
  AuthenticatedAdminReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminItemsRoute = AuthenticatedAdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGatewaysRoute =
  AuthenticatedAdminGatewaysRouteImport.update({
    id: '/gateways',
    path: '/gateways',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminChefsRoute = AuthenticatedAdminChefsRouteImport.update({
  id: '/chefs',
  path: '/chefs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedChefVerifyPayoutRoute =
  AuthenticatedChefVerifyPayoutRouteImport.update({
    id: '/payout',
    path: '/payout',
    getParentRoute: () => AuthenticatedChefVerifyRoute,
  } as any)
const AuthenticatedChefVerifyIdRoute =
  AuthenticatedChefVerifyIdRouteImport.update({
    id: '/id',
    path: '/id',
    getParentRoute: () => AuthenticatedChefVerifyRoute,
  } as any)
const AuthenticatedChefVerifyHealthRoute =
  AuthenticatedChefVerifyHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedChefVerifyRoute,
  } as any)
const AuthenticatedChefVerifyCapacityRoute =
  AuthenticatedChefVerifyCapacityRouteImport.update({
    id: '/capacity',
    path: '/capacity',
    getParentRoute: () => AuthenticatedChefVerifyRoute,
  } as any)
const AuthenticatedChefVerifyAddressRoute =
  AuthenticatedChefVerifyAddressRouteImport.update({
    id: '/address',
    path: '/address',
    getParentRoute: () => AuthenticatedChefVerifyRoute,
  } as any)
const AuthenticatedAdminChefsChefIdRoute =
  AuthenticatedAdminChefsChefIdRouteImport.update({
    id: '/$chefId',
    path: '/$chefId',
    getParentRoute: () => AuthenticatedAdminChefsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/chef': typeof AuthenticatedChefRouteRouteWithChildren
  '/delivery': typeof AuthenticatedDeliveryRouteRouteWithChildren
  '/browse': typeof AuthenticatedBrowseRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chefs': typeof AuthenticatedAdminChefsRouteWithChildren
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/receipts': typeof AuthenticatedAdminReceiptsRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/chef/insights': typeof AuthenticatedChefInsightsRoute
  '/chef/menu': typeof AuthenticatedChefMenuRoute
  '/chef/orders': typeof AuthenticatedChefOrdersRoute
  '/chef/payouts': typeof AuthenticatedChefPayoutsRoute
  '/chef/profile': typeof AuthenticatedChefProfileRoute
  '/chef/verify': typeof AuthenticatedChefVerifyRouteWithChildren
  '/chefs/$chefId': typeof AuthenticatedChefsChefIdRoute
  '/delivery/active': typeof AuthenticatedDeliveryActiveRoute
  '/delivery/jobs': typeof AuthenticatedDeliveryJobsRoute
  '/delivery/profile': typeof AuthenticatedDeliveryProfileRoute
  '/items/$chefItemId': typeof AuthenticatedItemsChefItemIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/chef/': typeof AuthenticatedChefIndexRoute
  '/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/admin/chefs/$chefId': typeof AuthenticatedAdminChefsChefIdRoute
  '/chef/verify/address': typeof AuthenticatedChefVerifyAddressRoute
  '/chef/verify/capacity': typeof AuthenticatedChefVerifyCapacityRoute
  '/chef/verify/health': typeof AuthenticatedChefVerifyHealthRoute
  '/chef/verify/id': typeof AuthenticatedChefVerifyIdRoute
  '/chef/verify/payout': typeof AuthenticatedChefVerifyPayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chefs': typeof AuthenticatedAdminChefsRouteWithChildren
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/receipts': typeof AuthenticatedAdminReceiptsRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/chef/insights': typeof AuthenticatedChefInsightsRoute
  '/chef/menu': typeof AuthenticatedChefMenuRoute
  '/chef/orders': typeof AuthenticatedChefOrdersRoute
  '/chef/payouts': typeof AuthenticatedChefPayoutsRoute
  '/chef/profile': typeof AuthenticatedChefProfileRoute
  '/chef/verify': typeof AuthenticatedChefVerifyRouteWithChildren
  '/chefs/$chefId': typeof AuthenticatedChefsChefIdRoute
  '/delivery/active': typeof AuthenticatedDeliveryActiveRoute
  '/delivery/jobs': typeof AuthenticatedDeliveryJobsRoute
  '/delivery/profile': typeof AuthenticatedDeliveryProfileRoute
  '/items/$chefItemId': typeof AuthenticatedItemsChefItemIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/chef': typeof AuthenticatedChefIndexRoute
  '/delivery': typeof AuthenticatedDeliveryIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/admin/chefs/$chefId': typeof AuthenticatedAdminChefsChefIdRoute
  '/chef/verify/address': typeof AuthenticatedChefVerifyAddressRoute
  '/chef/verify/capacity': typeof AuthenticatedChefVerifyCapacityRoute
  '/chef/verify/health': typeof AuthenticatedChefVerifyHealthRoute
  '/chef/verify/id': typeof AuthenticatedChefVerifyIdRoute
  '/chef/verify/payout': typeof AuthenticatedChefVerifyPayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/chef': typeof AuthenticatedChefRouteRouteWithChildren
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRouteRouteWithChildren
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/memberships': typeof AuthenticatedMembershipsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/chefs': typeof AuthenticatedAdminChefsRouteWithChildren
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/_authenticated/admin/items': typeof AuthenticatedAdminItemsRoute
  '/_authenticated/admin/receipts': typeof AuthenticatedAdminReceiptsRoute
  '/_authenticated/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/_authenticated/chef/insights': typeof AuthenticatedChefInsightsRoute
  '/_authenticated/chef/menu': typeof AuthenticatedChefMenuRoute
  '/_authenticated/chef/orders': typeof AuthenticatedChefOrdersRoute
  '/_authenticated/chef/payouts': typeof AuthenticatedChefPayoutsRoute
  '/_authenticated/chef/profile': typeof AuthenticatedChefProfileRoute
  '/_authenticated/chef/verify': typeof AuthenticatedChefVerifyRouteWithChildren
  '/_authenticated/chefs/$chefId': typeof AuthenticatedChefsChefIdRoute
  '/_authenticated/delivery/active': typeof AuthenticatedDeliveryActiveRoute
  '/_authenticated/delivery/jobs': typeof AuthenticatedDeliveryJobsRoute
  '/_authenticated/delivery/profile': typeof AuthenticatedDeliveryProfileRoute
  '/_authenticated/items/$chefItemId': typeof AuthenticatedItemsChefItemIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/chef/': typeof AuthenticatedChefIndexRoute
  '/_authenticated/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/admin/chefs/$chefId': typeof AuthenticatedAdminChefsChefIdRoute
  '/_authenticated/chef/verify/address': typeof AuthenticatedChefVerifyAddressRoute
  '/_authenticated/chef/verify/capacity': typeof AuthenticatedChefVerifyCapacityRoute
  '/_authenticated/chef/verify/health': typeof AuthenticatedChefVerifyHealthRoute
  '/_authenticated/chef/verify/id': typeof AuthenticatedChefVerifyIdRoute
  '/_authenticated/chef/verify/payout': typeof AuthenticatedChefVerifyPayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chef'
    | '/delivery'
    | '/browse'
    | '/cart'
    | '/dashboard'
    | '/memberships'
    | '/profile'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/chefs'
    | '/admin/drivers'
    | '/admin/gateways'
    | '/admin/items'
    | '/admin/receipts'
    | '/admin/zones'
    | '/chef/insights'
    | '/chef/menu'
    | '/chef/orders'
    | '/chef/payouts'
    | '/chef/profile'
    | '/chef/verify'
    | '/chefs/$chefId'
    | '/delivery/active'
    | '/delivery/jobs'
    | '/delivery/profile'
    | '/items/$chefItemId'
    | '/orders/$orderId'
    | '/admin/'
    | '/chef/'
    | '/delivery/'
    | '/groups/'
    | '/orders/'
    | '/admin/chefs/$chefId'
    | '/chef/verify/address'
    | '/chef/verify/capacity'
    | '/chef/verify/health'
    | '/chef/verify/id'
    | '/chef/verify/payout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/dashboard'
    | '/memberships'
    | '/profile'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/chefs'
    | '/admin/drivers'
    | '/admin/gateways'
    | '/admin/items'
    | '/admin/receipts'
    | '/admin/zones'
    | '/chef/insights'
    | '/chef/menu'
    | '/chef/orders'
    | '/chef/payouts'
    | '/chef/profile'
    | '/chef/verify'
    | '/chefs/$chefId'
    | '/delivery/active'
    | '/delivery/jobs'
    | '/delivery/profile'
    | '/items/$chefItemId'
    | '/orders/$orderId'
    | '/admin'
    | '/chef'
    | '/delivery'
    | '/groups'
    | '/orders'
    | '/admin/chefs/$chefId'
    | '/chef/verify/address'
    | '/chef/verify/capacity'
    | '/chef/verify/health'
    | '/chef/verify/id'
    | '/chef/verify/payout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/chef'
    | '/_authenticated/delivery'
    | '/_authenticated/browse'
    | '/_authenticated/cart'
    | '/_authenticated/dashboard'
    | '/_authenticated/memberships'
    | '/_authenticated/profile'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/chefs'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/gateways'
    | '/_authenticated/admin/items'
    | '/_authenticated/admin/receipts'
    | '/_authenticated/admin/zones'
    | '/_authenticated/chef/insights'
    | '/_authenticated/chef/menu'
    | '/_authenticated/chef/orders'
    | '/_authenticated/chef/payouts'
    | '/_authenticated/chef/profile'
    | '/_authenticated/chef/verify'
    | '/_authenticated/chefs/$chefId'
    | '/_authenticated/delivery/active'
    | '/_authenticated/delivery/jobs'
    | '/_authenticated/delivery/profile'
    | '/_authenticated/items/$chefItemId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/admin/'
    | '/_authenticated/chef/'
    | '/_authenticated/delivery/'
    | '/_authenticated/groups/'
    | '/_authenticated/orders/'
    | '/_authenticated/admin/chefs/$chefId'
    | '/_authenticated/chef/verify/address'
    | '/_authenticated/chef/verify/capacity'
    | '/_authenticated/chef/verify/health'
    | '/_authenticated/chef/verify/id'
    | '/_authenticated/chef/verify/payout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memberships': {
      id: '/_authenticated/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AuthenticatedMembershipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chef': {
      id: '/_authenticated/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof AuthenticatedChefRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery/': {
      id: '/_authenticated/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof AuthenticatedDeliveryIndexRouteImport
      parentRoute: typeof AuthenticatedDeliveryRouteRoute
    }
    '/_authenticated/chef/': {
      id: '/_authenticated/chef/'
      path: '/'
      fullPath: '/chef/'
      preLoaderRoute: typeof AuthenticatedChefIndexRouteImport
      parentRoute: typeof AuthenticatedChefRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items/$chefItemId': {
      id: '/_authenticated/items/$chefItemId'
      path: '/items/$chefItemId'
      fullPath: '/items/$chefItemId'
      preLoaderRoute: typeof AuthenticatedItemsChefItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery/profile': {
      id: '/_authenticated/delivery/profile'
      path: '/profile'
      fullPath: '/delivery/profile'
      preLoaderRoute: typeof AuthenticatedDeliveryProfileRouteImport
      parentRoute: typeof AuthenticatedDeliveryRouteRoute
    }
    '/_authenticated/delivery/jobs': {
      id: '/_authenticated/delivery/jobs'
      path: '/jobs'
      fullPath: '/delivery/jobs'
      preLoaderRoute: typeof AuthenticatedDeliveryJobsRouteImport
      parentRoute: typeof AuthenticatedDeliveryRouteRoute
    }
    '/_authenticated/delivery/active': {
      id: '/_authenticated/delivery/active'
      path: '/active'
      fullPath: '/delivery/active'
      preLoaderRoute: typeof AuthenticatedDeliveryActiveRouteImport
      parentRoute: typeof AuthenticatedDeliveryRouteRoute
    }
    '/_authenticated/chefs/$chefId': {
      id: '/_authenticated/chefs/$chefId'
      path: '/chefs/$chefId'
      fullPath: '/chefs/$chefId'
      preLoaderRoute: typeof AuthenticatedChefsChefIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chef/verify': {
      id: '/_authenticated/chef/verify'
      path: '/verify'
      fullPath: '/chef/verify'
      preLoaderRoute: typeof AuthenticatedChefVerifyRouteImport
      parentRoute: typeof AuthenticatedChefRouteRoute
    }
    '/_authenticated/chef/profile': {
      id: '/_authenticated/chef/profile'
      path: '/profile'
      fullPath: '/chef/profile'
      preLoaderRoute: typeof AuthenticatedChefProfileRouteImport
      parentRoute: typeof AuthenticatedChefRouteRoute
    }
    '/_authenticated/chef/payouts': {
      id: '/_authenticated/chef/payouts'
      path: '/payouts'
      fullPath: '/chef/payouts'
      preLoaderRoute: typeof AuthenticatedChefPayoutsRouteImport
      parentRoute: typeof AuthenticatedChefRouteRoute
    }
    '/_authenticated/chef/orders': {
      id: '/_authenticated/chef/orders'
      path: '/orders'
      fullPath: '/chef/orders'
      preLoaderRoute: typeof AuthenticatedChefOrdersRouteImport
      parentRoute: typeof AuthenticatedChefRouteRoute
    }
    '/_authenticated/chef/menu': {
      id: '/_authenticated/chef/menu'
      path: '/menu'
      fullPath: '/chef/menu'
      preLoaderRoute: typeof AuthenticatedChefMenuRouteImport
      parentRoute: typeof AuthenticatedChefRouteRoute
    }
    '/_authenticated/chef/insights': {
      id: '/_authenticated/chef/insights'
      path: '/insights'
      fullPath: '/chef/insights'
      preLoaderRoute: typeof AuthenticatedChefInsightsRouteImport
      parentRoute: typeof AuthenticatedChefRouteRoute
    }
    '/_authenticated/admin/zones': {
      id: '/_authenticated/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AuthenticatedAdminZonesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/receipts': {
      id: '/_authenticated/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AuthenticatedAdminReceiptsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/items': {
      id: '/_authenticated/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AuthenticatedAdminItemsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gateways': {
      id: '/_authenticated/admin/gateways'
      path: '/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AuthenticatedAdminGatewaysRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/chefs': {
      id: '/_authenticated/admin/chefs'
      path: '/chefs'
      fullPath: '/admin/chefs'
      preLoaderRoute: typeof AuthenticatedAdminChefsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/chef/verify/payout': {
      id: '/_authenticated/chef/verify/payout'
      path: '/payout'
      fullPath: '/chef/verify/payout'
      preLoaderRoute: typeof AuthenticatedChefVerifyPayoutRouteImport
      parentRoute: typeof AuthenticatedChefVerifyRoute
    }
    '/_authenticated/chef/verify/id': {
      id: '/_authenticated/chef/verify/id'
      path: '/id'
      fullPath: '/chef/verify/id'
      preLoaderRoute: typeof AuthenticatedChefVerifyIdRouteImport
      parentRoute: typeof AuthenticatedChefVerifyRoute
    }
    '/_authenticated/chef/verify/health': {
      id: '/_authenticated/chef/verify/health'
      path: '/health'
      fullPath: '/chef/verify/health'
      preLoaderRoute: typeof AuthenticatedChefVerifyHealthRouteImport
      parentRoute: typeof AuthenticatedChefVerifyRoute
    }
    '/_authenticated/chef/verify/capacity': {
      id: '/_authenticated/chef/verify/capacity'
      path: '/capacity'
      fullPath: '/chef/verify/capacity'
      preLoaderRoute: typeof AuthenticatedChefVerifyCapacityRouteImport
      parentRoute: typeof AuthenticatedChefVerifyRoute
    }
    '/_authenticated/chef/verify/address': {
      id: '/_authenticated/chef/verify/address'
      path: '/address'
      fullPath: '/chef/verify/address'
      preLoaderRoute: typeof AuthenticatedChefVerifyAddressRouteImport
      parentRoute: typeof AuthenticatedChefVerifyRoute
    }
    '/_authenticated/admin/chefs/$chefId': {
      id: '/_authenticated/admin/chefs/$chefId'
      path: '/$chefId'
      fullPath: '/admin/chefs/$chefId'
      preLoaderRoute: typeof AuthenticatedAdminChefsChefIdRouteImport
      parentRoute: typeof AuthenticatedAdminChefsRoute
    }
  }
}

interface AuthenticatedAdminChefsRouteChildren {
  AuthenticatedAdminChefsChefIdRoute: typeof AuthenticatedAdminChefsChefIdRoute
}

const AuthenticatedAdminChefsRouteChildren: AuthenticatedAdminChefsRouteChildren =
  {
    AuthenticatedAdminChefsChefIdRoute: AuthenticatedAdminChefsChefIdRoute,
  }

const AuthenticatedAdminChefsRouteWithChildren =
  AuthenticatedAdminChefsRoute._addFileChildren(
    AuthenticatedAdminChefsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminChefsRoute: typeof AuthenticatedAdminChefsRouteWithChildren
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminGatewaysRoute: typeof AuthenticatedAdminGatewaysRoute
  AuthenticatedAdminItemsRoute: typeof AuthenticatedAdminItemsRoute
  AuthenticatedAdminReceiptsRoute: typeof AuthenticatedAdminReceiptsRoute
  AuthenticatedAdminZonesRoute: typeof AuthenticatedAdminZonesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminChefsRoute: AuthenticatedAdminChefsRouteWithChildren,
    AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
    AuthenticatedAdminGatewaysRoute: AuthenticatedAdminGatewaysRoute,
    AuthenticatedAdminItemsRoute: AuthenticatedAdminItemsRoute,
    AuthenticatedAdminReceiptsRoute: AuthenticatedAdminReceiptsRoute,
    AuthenticatedAdminZonesRoute: AuthenticatedAdminZonesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedChefVerifyRouteChildren {
  AuthenticatedChefVerifyAddressRoute: typeof AuthenticatedChefVerifyAddressRoute
  AuthenticatedChefVerifyCapacityRoute: typeof AuthenticatedChefVerifyCapacityRoute
  AuthenticatedChefVerifyHealthRoute: typeof AuthenticatedChefVerifyHealthRoute
  AuthenticatedChefVerifyIdRoute: typeof AuthenticatedChefVerifyIdRoute
  AuthenticatedChefVerifyPayoutRoute: typeof AuthenticatedChefVerifyPayoutRoute
}

const AuthenticatedChefVerifyRouteChildren: AuthenticatedChefVerifyRouteChildren =
  {
    AuthenticatedChefVerifyAddressRoute: AuthenticatedChefVerifyAddressRoute,
    AuthenticatedChefVerifyCapacityRoute: AuthenticatedChefVerifyCapacityRoute,
    AuthenticatedChefVerifyHealthRoute: AuthenticatedChefVerifyHealthRoute,
    AuthenticatedChefVerifyIdRoute: AuthenticatedChefVerifyIdRoute,
    AuthenticatedChefVerifyPayoutRoute: AuthenticatedChefVerifyPayoutRoute,
  }

const AuthenticatedChefVerifyRouteWithChildren =
  AuthenticatedChefVerifyRoute._addFileChildren(
    AuthenticatedChefVerifyRouteChildren,
  )

interface AuthenticatedChefRouteRouteChildren {
  AuthenticatedChefInsightsRoute: typeof AuthenticatedChefInsightsRoute
  AuthenticatedChefMenuRoute: typeof AuthenticatedChefMenuRoute
  AuthenticatedChefOrdersRoute: typeof AuthenticatedChefOrdersRoute
  AuthenticatedChefPayoutsRoute: typeof AuthenticatedChefPayoutsRoute
  AuthenticatedChefProfileRoute: typeof AuthenticatedChefProfileRoute
  AuthenticatedChefVerifyRoute: typeof AuthenticatedChefVerifyRouteWithChildren
  AuthenticatedChefIndexRoute: typeof AuthenticatedChefIndexRoute
}

const AuthenticatedChefRouteRouteChildren: AuthenticatedChefRouteRouteChildren =
  {
    AuthenticatedChefInsightsRoute: AuthenticatedChefInsightsRoute,
    AuthenticatedChefMenuRoute: AuthenticatedChefMenuRoute,
    AuthenticatedChefOrdersRoute: AuthenticatedChefOrdersRoute,
    AuthenticatedChefPayoutsRoute: AuthenticatedChefPayoutsRoute,
    AuthenticatedChefProfileRoute: AuthenticatedChefProfileRoute,
    AuthenticatedChefVerifyRoute: AuthenticatedChefVerifyRouteWithChildren,
    AuthenticatedChefIndexRoute: AuthenticatedChefIndexRoute,
  }

const AuthenticatedChefRouteRouteWithChildren =
  AuthenticatedChefRouteRoute._addFileChildren(
    AuthenticatedChefRouteRouteChildren,
  )

interface AuthenticatedDeliveryRouteRouteChildren {
  AuthenticatedDeliveryActiveRoute: typeof AuthenticatedDeliveryActiveRoute
  AuthenticatedDeliveryJobsRoute: typeof AuthenticatedDeliveryJobsRoute
  AuthenticatedDeliveryProfileRoute: typeof AuthenticatedDeliveryProfileRoute
  AuthenticatedDeliveryIndexRoute: typeof AuthenticatedDeliveryIndexRoute
}

const AuthenticatedDeliveryRouteRouteChildren: AuthenticatedDeliveryRouteRouteChildren =
  {
    AuthenticatedDeliveryActiveRoute: AuthenticatedDeliveryActiveRoute,
    AuthenticatedDeliveryJobsRoute: AuthenticatedDeliveryJobsRoute,
    AuthenticatedDeliveryProfileRoute: AuthenticatedDeliveryProfileRoute,
    AuthenticatedDeliveryIndexRoute: AuthenticatedDeliveryIndexRoute,
  }

const AuthenticatedDeliveryRouteRouteWithChildren =
  AuthenticatedDeliveryRouteRoute._addFileChildren(
    AuthenticatedDeliveryRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedChefRouteRoute: typeof AuthenticatedChefRouteRouteWithChildren
  AuthenticatedDeliveryRouteRoute: typeof AuthenticatedDeliveryRouteRouteWithChildren
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMembershipsRoute: typeof AuthenticatedMembershipsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedChefsChefIdRoute: typeof AuthenticatedChefsChefIdRoute
  AuthenticatedItemsChefItemIdRoute: typeof AuthenticatedItemsChefItemIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedChefRouteRoute: AuthenticatedChefRouteRouteWithChildren,
  AuthenticatedDeliveryRouteRoute: AuthenticatedDeliveryRouteRouteWithChildren,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMembershipsRoute: AuthenticatedMembershipsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedChefsChefIdRoute: AuthenticatedChefsChefIdRoute,
  AuthenticatedItemsChefItemIdRoute: AuthenticatedItemsChefItemIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
