/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedItemsChefItemIdRouteImport } from './routes/_authenticated/items.$chefItemId'
import { Route as AuthenticatedChefsChefIdRouteImport } from './routes/_authenticated/chefs.$chefId'
import { Route as AuthenticatedAdminZonesRouteImport } from './routes/_authenticated/admin/zones'
import { Route as AuthenticatedAdminItemsRouteImport } from './routes/_authenticated/admin/items'
import { Route as AuthenticatedAdminGatewaysRouteImport } from './routes/_authenticated/admin/gateways'
import { Route as AuthenticatedAdminChefsRouteImport } from './routes/_authenticated/admin/chefs'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedItemsChefItemIdRoute =
  AuthenticatedItemsChefItemIdRouteImport.update({
    id: '/items/$chefItemId',
    path: '/items/$chefItemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChefsChefIdRoute =
  AuthenticatedChefsChefIdRouteImport.update({
    id: '/chefs/$chefId',
    path: '/chefs/$chefId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminZonesRoute = AuthenticatedAdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminItemsRoute = AuthenticatedAdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGatewaysRoute =
  AuthenticatedAdminGatewaysRouteImport.update({
    id: '/gateways',
    path: '/gateways',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminChefsRoute = AuthenticatedAdminChefsRouteImport.update({
  id: '/chefs',
  path: '/chefs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/browse': typeof AuthenticatedBrowseRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chefs': typeof AuthenticatedAdminChefsRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/chefs/$chefId': typeof AuthenticatedChefsChefIdRoute
  '/items/$chefItemId': typeof AuthenticatedItemsChefItemIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chefs': typeof AuthenticatedAdminChefsRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/chefs/$chefId': typeof AuthenticatedChefsChefIdRoute
  '/items/$chefItemId': typeof AuthenticatedItemsChefItemIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/chefs': typeof AuthenticatedAdminChefsRoute
  '/_authenticated/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/_authenticated/admin/items': typeof AuthenticatedAdminItemsRoute
  '/_authenticated/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/_authenticated/chefs/$chefId': typeof AuthenticatedChefsChefIdRoute
  '/_authenticated/items/$chefItemId': typeof AuthenticatedItemsChefItemIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/browse'
    | '/cart'
    | '/dashboard'
    | '/admin/categories'
    | '/admin/chefs'
    | '/admin/gateways'
    | '/admin/items'
    | '/admin/zones'
    | '/chefs/$chefId'
    | '/items/$chefItemId'
    | '/admin/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/dashboard'
    | '/admin/categories'
    | '/admin/chefs'
    | '/admin/gateways'
    | '/admin/items'
    | '/admin/zones'
    | '/chefs/$chefId'
    | '/items/$chefItemId'
    | '/admin'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/browse'
    | '/_authenticated/cart'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/chefs'
    | '/_authenticated/admin/gateways'
    | '/_authenticated/admin/items'
    | '/_authenticated/admin/zones'
    | '/_authenticated/chefs/$chefId'
    | '/_authenticated/items/$chefItemId'
    | '/_authenticated/admin/'
    | '/_authenticated/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/items/$chefItemId': {
      id: '/_authenticated/items/$chefItemId'
      path: '/items/$chefItemId'
      fullPath: '/items/$chefItemId'
      preLoaderRoute: typeof AuthenticatedItemsChefItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chefs/$chefId': {
      id: '/_authenticated/chefs/$chefId'
      path: '/chefs/$chefId'
      fullPath: '/chefs/$chefId'
      preLoaderRoute: typeof AuthenticatedChefsChefIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/zones': {
      id: '/_authenticated/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AuthenticatedAdminZonesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/items': {
      id: '/_authenticated/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AuthenticatedAdminItemsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gateways': {
      id: '/_authenticated/admin/gateways'
      path: '/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AuthenticatedAdminGatewaysRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/chefs': {
      id: '/_authenticated/admin/chefs'
      path: '/chefs'
      fullPath: '/admin/chefs'
      preLoaderRoute: typeof AuthenticatedAdminChefsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminChefsRoute: typeof AuthenticatedAdminChefsRoute
  AuthenticatedAdminGatewaysRoute: typeof AuthenticatedAdminGatewaysRoute
  AuthenticatedAdminItemsRoute: typeof AuthenticatedAdminItemsRoute
  AuthenticatedAdminZonesRoute: typeof AuthenticatedAdminZonesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminChefsRoute: AuthenticatedAdminChefsRoute,
    AuthenticatedAdminGatewaysRoute: AuthenticatedAdminGatewaysRoute,
    AuthenticatedAdminItemsRoute: AuthenticatedAdminItemsRoute,
    AuthenticatedAdminZonesRoute: AuthenticatedAdminZonesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedChefsChefIdRoute: typeof AuthenticatedChefsChefIdRoute
  AuthenticatedItemsChefItemIdRoute: typeof AuthenticatedItemsChefItemIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedChefsChefIdRoute: AuthenticatedChefsChefIdRoute,
  AuthenticatedItemsChefItemIdRoute: AuthenticatedItemsChefItemIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
